# Generated by Django 5.0.6 on 2024-07-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_adimin',
            new_name='is_admin',
        ),
    ]
