# Generated by Django 5.0.6 on 2024-07-04 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0007_user_dept_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept', to='ems.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='ems.role'),
        ),
    ]
