# Generated by Django 5.0.6 on 2024-07-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0010_leave_session_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hours_worked',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
