# Generated by Django 5.0.6 on 2024-07-04 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0011_user_hours_worked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='start_date',
            new_name='start',
        ),
        migrations.AddField(
            model_name='events',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
