# Generated by Django 5.0.6 on 2024-07-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0013_user_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
