# Generated by Django 5.0.6 on 2024-07-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0014_leave_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
