# Generated by Django 5.0.6 on 2024-07-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0016_remove_user_messages_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='start',
        ),
    ]
