# Generated by Django 5.0.6 on 2024-07-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0017_remove_task_start'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
