# Generated by Django 5.0.6 on 2024-07-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0018_delete_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
