# Generated by Django 5.0.6 on 2024-07-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0023_task_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hours_worked',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
