# Generated by Django 5.0.6 on 2024-07-10 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0024_task_hours_worked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='hours_worked',
            new_name='perfomance',
        ),
    ]
